### ISSUE TITLE
Hash e instrucciones de inicialización a la app

### ISSUE THREAD

**Issue by AbrahamS314** [simbadMarino/dCloud#16]
Como primer punto seria que la hora de subir algún archivo a btfs no solo del hash que comienza por "Qm..." si no, que genere el link directo para compartirlo o tenerlo a salvo y entrar a descargar en cualquier momento, ejemplo:

que genere este link
**https://gateway.btfs.io/btfs/QmUPTiFPiJW932ejkMKCm7JwMBWYisWPrzYJDe4AJ4Zxij**

y no solo el hash **QmUPTiFPiJW932ejkMKCm7JwMBWYisWPrzYJDe4AJ4Zxij**

Como segundo punto, incluir un botón que abra como un texto instructivo de inicialización por primera vez a la app, que guie al usuario por una serie de pasos, desde configurar para activar el sistema btfs como luego a que haga el depósito de los btt y posteriormente los swaps para recargar saldo al la wallet vault y luego si usar subir los archivos...

**Comment by simbadMarino** [comment]
Hola @AbrahamS314 ! Gracias por la retroalimentacion, lo del link es posible y facil de implementar, en cuanto a lo de la guia de configuracion y seteo del nodo es una buena idea, lo dejare como prioridad 2 de implementacion. Espero armar un roadmap pronto con todos los elementos a incluir en futuras versiones de dCloud!

**Comment by simbadMarino** [comment]
Este issue puede cerrarse a partir de la version 1.6.0, misma que añade una guía de inicialización, además de que se agrego ya el link de descarga al finalizar la subida.

Gracias! /Thank you!
